###
POST http://127.0.0.1:8088/shorturl/generate
accept: application/json
Content-Type: application/json

{
    "url": "https://github.com/i4erkasov/quadcode-test-uri-minifier/blob/master/README.md123"
}

###
GET http://127.0.0.1:8088/shorturl/limits/3
accept: application/json
###

###
GET http://127.0.0.1:8088/statistic/redirect
accept: application/json
###

###
GET http://127.0.0.1:8088/statistic/redirect/2
accept: application/json
###





